[package]
name = "generator"
version = "0.1.0"
edition = "2021"
authors = ["🇫🇷 Romain TRUCHI <romain.truchi.06@gmail.com>"]

[dependencies]
regex = "1.10.2"
reqwest = "0.11.22"
scraper = "0.18.1"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
tokio = { version = "1.35.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
weedle = "0.12.0"
